config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  apipie
  resources :accounts
  get 'home/index'
  devise_for :users
  root to: 'home#index'

  namespace :api do
    resources :accounts, only: %i[create show]
    resources :transactions, only: %i[create show]
    post 'transferir', to: 'transactions#transfer'
    post 'sacar', to: 'transactions#withdraw'
  end
  resources :conta, controller: 'accounts', only: %i[create show]
  resources :transacao, controller: 'transactions', only: %i[create show]
end

app/models/account.rb
# frozen_string_literal: true

class Account < ApplicationRecord
  belongs_to :user
  validates :balance, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/accounts_controller.rb
# frozen_string_literal: true

class AccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_account, only: %i[show edit update destroy]

  # GET /accounts or /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1 or /accounts/1.json
  def show; end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit; end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to account_url(@account), notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to account_url(@account), notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    @account.destroy!

    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_account
    @account = Account.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def account_params
    params.require(:account).permit(:name, :balance)
  end
end

app/controllers/api/accounts_controller.rb
# frozen_string_literal: true

# Controller for Account
module Api
  class AccountsController < ApplicationController
    skip_before_action :verify_authenticity_token

    api :POST, '/conta', 'Cria uma nova conta de usuário'
    param :email, String, desc: 'E-mail do usuário', required: true
    param :nome, String, desc: 'Nome do usuário', required: true
    param :saldo, Float, desc: 'Saldo inicial da conta', required: true
    param :senha, String, desc: 'Senha para o usuário', required: false
    error code: 422, desc: 'Unprocessable Entity'

    def create
      password = params[:senha] || 'changeme'
      user = User.new(email: params[:email], password:, password_confirmation: password,
                      name: params[:nome])
      if user.save
        account = user.account
        account.update(balance: params[:saldo])
        render json: account, status: :created
      else
        render json: { errors: user.errors.full_messages }, status: :unprocessable_entity
      end
    end

    api :GET, '/conta/:id', 'Exibe uma conta de usuário'
    param :id, :number, desc: 'ID da conta', required: true
    error code: 404, desc: 'Conta não encontrada'

    def show
      account = Account.find_by(id: params[:id])
      if account
        render json: account, status: :ok
      else
        render json: { error: 'Account not found' }, status: :not_found
      end
    end
  end
end

app/views/accounts/_account.html.slim
div id="#{dom_id account}"
  p
    strong Name:
    =< account.name
  p
    strong Balance:
    =< account.balance

app/views/accounts/_form.html.slim
= form_with(model: account) do |form|
  - if account.errors.any?
    div style="color: red"
      h2 = "#{pluralize(account.errors.count, "error")} prohibited this account from being saved:"
      ul
        - account.errors.each do |error|
          li = error.full_message

  div
    = form.label :name, style: "display: block"
    = form.text_field :name

  div
    = form.label :balance, style: "display: block"
    = form.text_field :balance

  div
    = form.submit

app/views/accounts/edit.html.slim
h1 Editing account

== render "form", account: @account

br

div
  => link_to "Show this account", @account
  '|
  =< link_to "Back to accounts", accounts_path

app/views/accounts/index.html.slim
p style="color: green" = notice

h1 Accounts

#accounts
  - @accounts.each do |account|
    == render account
    p
      = link_to "Show this account", account

= link_to "New account", new_account_path

app/views/accounts/new.html.slim
h1 New account

== render "form", account: @account

br

div
  = link_to "Back to accounts", accounts_path

app/views/accounts/show.html.slim
p style="color: green" = notice

== render @account

div
  => link_to "Edit this account", edit_account_path(@account)
  '|
  =< link_to "Back to accounts", accounts_path

  = button_to "Destroy this account", @account, method: :delete